name: CI Static Validations

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: 17

      - name: Spotless Check
        run: ./gradlew spotlessCheck --stacktrace

      - name: Lint
        run: ./gradlew lint --stacktrace

      - name: Upload Precompose Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: precompose-lint-report
          path: precompose/build/reports

      - name: Upload Precompose Molecule Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: precompose-molecule-lint-report
          path: precompose-molecule/build/reports

      - name: Upload Precompose ViewModel Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: precompose-viewmodel-lint-report
          path: precompose-viewmodel/build/reports

  call-build:
    needs: validate
    uses: ./.github/workflows/build.yml
    secrets: inherit
